config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show] #追記 ユーザーマイページへのルーティング


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :messages, only: [:create]
    
  end
resources :maps 
get 'hello/index' => 'hello#index'
root 'hello#index'

resources :relationships, only: [:create, :destroy]
resources :rooms, only: [:show, :create, :index] do
  member do
    get 'inviting' => 'users#invite'
    post '/users/:user_id/entries' => 'entries#create', as: 'entries'
  end
  resources :chats, only: [:create]


end

delete 'rooms/:room_id/users/:user_id/entries' => 'entries#destroy', as: 'entry'
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :user
    belongs_to :room

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/entry.rb
class Entry < ApplicationRecord
    belongs_to :user
    belongs_to :room
    
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/map.rb
class Map < ApplicationRecord
    geocoded_by :address
    after_validation :geocode
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user    
    has_many :post_tags, dependent: :destroy
    has_many :tags, through: :post_tags
    has_many :messages, dependent: :destroy
    #belongs_to :room
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"

    #自分がフォローしているユーザー
    belongs_to :following, class_name: "User"

    #バリデーション
    validates :follower_id, presence: true
    validates :following_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :user_rooms
    has_many :users, through: :user_rooms
    has_many :chats
    has_many :entries

end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :post_tags, dependent: :destroy
    has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :messages, dependent: :destroy

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship",  dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  has_many :user_rooms
  has_many :rooms, through: :user_rooms
  has_many :chats

  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 } #追記
  
  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end

  #フォローするときのメソッド
  def follow(user)
    following_relationships.create!(following_id: user.id)
  end

  #フォローを外すときのメソッド
  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end

  def already_liked?(post)
      self.likes.exists?(post_id: post.id)
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
    belongs_to :user
    belongs_to :room
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
        def show
          @user = User.find(params[:id]) 
        end
        def invite
          @user =User.find(current_user.id)
        end
      
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/massages_helper.rb
module MassagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<div class="follower">
  <h5 style="color: black;">フォロワー<%= @user.followers.count %>人</h5>
</div>
<div class="follow">
  <h5 style="color: black;">フォロー<%= @user.following.count %>人</h5>
</div>
<div>
    <%= form_for(current_user, url: relationships_path, method: :post, remote: true) do |f| %>
        <%= hidden_field_tag :following_id, @user.id %>
        <%= f.submit "フォローする", class: "btn btn-outline-secondary" %>
    <% end %>
</div>

app/views/users/_follow_form.html.erb
<% if user_signed_in? && @user != current_user %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render "unfollow" %>
    <% else %>
      <%= render "follow" %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<div class="follower">
  <h5 style="color: black;">フォロワー<%= @user.followers.count %>人</h5>
</div>
<div class="follow">
  <h5 style="color: black;">フォロー<%= @user.following.count %>人</h5>
</div>
<div>
<%= form_for(current_user, url: relationship_path(@user), method: :delete, remote: true) do |f| %>
    <%= f.submit "フォロー解除", class: "btn btn-outline-secondary" %>
<% end %>
</div>

app/views/users/invite.html.erb
<%= stylesheet_link_tag 'users.invite', :media => "all" %>
<body>
<div class="header">
<h3>フォロー一覧</h3>
</div>

<div class ="main">
<% @user.following.each do |user| %>
    <% if Entry.exists?(user_id: user.id) %>
        <br><%= user.name %>さん 招待済み</br>
    <% else %>
        <%= link_to entries_room_path(id: params[:id], user_id: user.id), method: :post do %>
        <%= user.name %>
        <% end %>
    <% end %>
<% end %>
</div>
</body>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'user.show', :media => "all" %>
<body>
<div class ="top">
  <h1>マイページ</h1>
</div>
<div class = "main">
  <div class ="owndetail">
    <div class ="name">
      <p>ユーザーネーム :<%= @user.name %></p>
    </div>
    <div class ="mail">
      <p>メールアドレス : <%= @user.email %></p>
    </div>
    <div class ="profil">
      <p>プロフィール </p>
      <div class ="profil_box"> 
        <p><%= @user.profile %></p>
      </div>
      <%= render "follow_form" %>
      <% if current_user.id == @user.id %>
      <%= button_to "編集する", edit_user_registration_path %>
        <% end %>
    </div>
  </div>
  <h2>ユーザーの投稿</h2>
  <div class = "post">
    <% @user.posts.each do |t| %>
      <div class="postbox">
      <p>ユーザーネーム:</p><a href="/users/<%= t.user.id %>"><%= t.user.name %></a>
      <br><%= image_tag t.image_url, size: "320x280" if t.image? %></br>
      <p1>contents:<%= t.body %></p1>
      <% t.tags.each do |tag| %>
        <br>tag:<%= tag.name %></br>
      <% end %>
      
      </div>
    <% end %>
  </div>
  <h2>ユーザーがいいねした投稿一覧</h2>
  <div class ="post">
    
      <% @user.liked_posts.each do |t| %>
        <div class = "postbox" >
        <p><%= t.user.name %></p>
        <%= image_tag t.image_url, size: "320x280" if t.image? %>
        <% t.tags.each do |tag| %>
          <br>tag:<%= tag.name %></br>
        <% end %>
        <br><%= t.body %></br>
        </div>
      <% end %>
  </div>
</div>
<body>

