config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show] #追記 ユーザーマイページへのルーティング


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :messages, only: [:create]
    
  end
resources :maps 
get 'hello/index' => 'hello#index'
root 'hello#index'

resources :relationships, only: [:create, :destroy]
resources :rooms, only: [:show, :create, :index] do
  member do
    get 'inviting' => 'users#invite'
    post '/users/:user_id/entries' => 'entries#create', as: 'entries'
  end
  resources :chats, only: [:create]


end

delete 'rooms/:room_id/users/:user_id/entries' => 'entries#destroy', as: 'entry'
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :user
    belongs_to :room

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/entry.rb
class Entry < ApplicationRecord
    belongs_to :user
    belongs_to :room
    
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/map.rb
class Map < ApplicationRecord
    geocoded_by :address
    after_validation :geocode
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user    
    has_many :post_tags, dependent: :destroy
    has_many :tags, through: :post_tags
    has_many :messages, dependent: :destroy
    #belongs_to :room
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"

    #自分がフォローしているユーザー
    belongs_to :following, class_name: "User"

    #バリデーション
    validates :follower_id, presence: true
    validates :following_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :user_rooms
    has_many :users, through: :user_rooms
    has_many :chats
    has_many :entries

end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :post_tags, dependent: :destroy
    has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :messages, dependent: :destroy

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship",  dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  has_many :user_rooms
  has_many :rooms, through: :user_rooms
  has_many :chats

  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 } #追記
  
  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end

  #フォローするときのメソッド
  def follow(user)
    following_relationships.create!(following_id: user.id)
  end

  #フォローを外すときのメソッド
  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end

  def already_liked?(post)
      self.likes.exists?(post_id: post.id)
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
    belongs_to :user
    belongs_to :room
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @room = Room.find(params[:id])
    @posts = Chat.where(room_id:@room.id)
    @chat = Chat.new
  end
  def create
    @room = Room.new(room_params)
    @room.save
    current_user.user_rooms.create(room_id: @room.id)
    redirect_to @room

  end

  def index
      if user_signed_in?
        @room = Room.new
        @rooms = current_user.rooms
        @norooms_id = UserRoom.where.not(user_id:current_user.id)
        @entry_room = Entry.where(user_id:current_user.id)
      end
  end


  private

  def room_params
  params.require(:room).permit(:name)
  end

end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/massages_helper.rb
module MassagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rooms/index.html.erb
<%= stylesheet_link_tag 'rooms.index', :media => "all" %>

<div class = "make_talkroom">
<% if user_signed_in? %>
  <h2>トークルーム作成</h2>
</div>
<div class = "making_room">
<%= form_with model: @room do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>
</div>
<div class="room" >
  <div class = "joinedroom">
  <h5>参加済トークルーム一覧</h5>
  <% @rooms.each do |room| %>
    <%= link_to room_path(room.id) do %>
    <%= room.name %>
    <% end %>
  <% end %>
  </div>
  <div class = "invitedroom">
  <h5>招待されているトークルーム</h5>
  <% @entry_room.each do |entry| %>
    <%= link_to entry_path(entry.room.id,current_user.id), method: :delete do %>
    <%= entry.room.name %>
    <% end %>
  <% end %>
  </div>
</div>
<% end %>

app/views/rooms/show.html.erb
<%= stylesheet_link_tag 'rooms.show', :media => "all" %>

<div class ="header">
  <div class="room">
  <h1><%= "ルーム名：#{@room.name}" %></h1>
  </div>
</div>

<div class ="main">
  <div class ="content">
    <div class="posts">
      <% @posts.each do |post| %>
        <div class = "chatbox">
          <p><%= post.user.name %>さん</p>
          <p>><%= post.message %></p>
        </div>
      <% end %>
    </div>
    <div class ="post_content">
      <%= form_for [@room, @chat] do |f| %>
        <div class="field">
          <%= f.text_field :message, :size => 140 %>
          <%= f.submit "送信する" %>
          <%= link_to 'フォロワーをルームに招待する', inviting_room_path(room_id:params[:room_id], user_id:current_user.id) %>
        </div>
      <% end %>
    </div>
  </div>
</div>
