config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show] #追記 ユーザーマイページへのルーティング


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :messages, only: [:create]
    
  end
resources :maps 
get 'hello/index' => 'hello#index'
root 'hello#index'

resources :relationships, only: [:create, :destroy]
resources :rooms, only: [:show, :create, :index] do
  member do
    get 'inviting' => 'users#invite'
    post '/users/:user_id/entries' => 'entries#create', as: 'entries'
  end
  resources :chats, only: [:create]


end

delete 'rooms/:room_id/users/:user_id/entries' => 'entries#destroy', as: 'entry'
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :user
    belongs_to :room

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/entry.rb
class Entry < ApplicationRecord
    belongs_to :user
    belongs_to :room
    
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/map.rb
class Map < ApplicationRecord
    geocoded_by :address
    after_validation :geocode
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user    
    has_many :post_tags, dependent: :destroy
    has_many :tags, through: :post_tags
    has_many :messages, dependent: :destroy
    #belongs_to :room
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"

    #自分がフォローしているユーザー
    belongs_to :following, class_name: "User"

    #バリデーション
    validates :follower_id, presence: true
    validates :following_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :user_rooms
    has_many :users, through: :user_rooms
    has_many :chats
    has_many :entries

end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :post_tags, dependent: :destroy
    has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :messages, dependent: :destroy

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship",  dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  has_many :user_rooms
  has_many :rooms, through: :user_rooms
  has_many :chats

  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 } #追記
  
  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end

  #フォローするときのメソッド
  def follow(user)
    following_relationships.create!(following_id: user.id)
  end

  #フォローを外すときのメソッド
  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end

  def already_liked?(post)
      self.likes.exists?(post_id: post.id)
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
    belongs_to :user
    belongs_to :room
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  
    def index
      #@posts =Post.all
      @page = Post.all.page(params[:page]).per(3)
      
      @post = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
      @rank_posts = Post.all.sort {|a,b| b.liked_users.count <=> a.liked_users.count}  
    end
   
    def new
       @post = Post.new
    end
   
    def create
       post = Post.new(post_params)
       post.room_id = 0
       post.user_id = current_user.id
       if post.save
         redirect_to :action => "index"
       else
         redirect_to :action => "new"
       end
    end
    
    def show
        @post = Post.find(params[:id])
        @messages = @post.messages
        @message = Message.new
    end
    
    def edit
        @post = Post.find(params[:id])
    end

    def update
        post = Post.find(params[:id])
        if post.update(post_params)
          redirect_to :action => "show", :id => post.id
        else
          redirect_to :action => "new"
        end
    end
    def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to action: :index
    end
    private
    def post_params
      params.require(:post).permit(:lat,:lng,:body, :image, :title, tag_ids: [])
    end
    
    
    
    

end    

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/massages_helper.rb
module MassagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<div class="check_box">
    <span>タグ</span>
    <%= form.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
     <div>
       <%= tag.label do %>
         <%= tag.check_box %>
         <%= tag.text %>
       <% end %>
     </div>
   <% end %>
 </div>
 <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= stylesheet_link_tag 'edit', :media => "all" %>

<div class = "head">
  <h1>投稿編集</h1>
</div>
<div class = "main_content">
  <%= form_for @post do |f| %>
      <%= f.label :内容 %>
      <%= f.text_field :body, :size => 140  %> 
      <%= f.submit "編集する" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>
<!DOCTYPE html>
<html lang="ja">
<boby>
<div class= "top">
  <h1>投稿一覧</h1>
  <h5>Hobbyshare</h5>
</div>

<div class ="main_content">
  <%= form_tag posts_path, method: :get, class: 'boards__searchForm' do %>
    <%= select_tag :tag_id,
                  options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                  {
                    prompt: 'タグで絞り込み検索',
                    onchange: 'submit(this.form);'
                  }
    %>
  <% end %>


    <% if user_signed_in? %>
    <% end %>
    <div class = "post">
    <% @post.each do |t| %>
        <div class="postbox">
        <p>ユーザーネーム:</p><a href="/users/<%= t.user.id %>"><%= t.user.name %></a>
        <br><%= image_tag t.image_url, size: "320x280" if t.image? %></br>
        <p1><%= t.body %></p1>
        <% t.tags.each do |tag| %>
          <br>tag:<%= tag.name %></br>
        <% end %>
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% else %>
              <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                <i class="far fa-heart"></i><%= t.likes.count %>
              <% end %>
          <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>

        
        <%= t.created_at %>
        <%= link_to "詳細へ", post_path(t.id) %>
        <% if user_signed_in? && current_user.id == t.user_id %>
          <%= link_to "編集する", edit_post_path(t.id) %>
          <%= button_to "削除する", post_path(t.id), method: :delete %>
        <% end %>      
        </div>
    
      
    <% end %>
    </div>


  </div>
  <div class ="rankingbox">
    <h2>いいねランキング</h2>
      <% @rank_posts.each.with_index(1) do |t,i| %> 
      <div class ="rankbox1">
      <% if i==1 %>
        1位  
        <div class="rank1">
            ユーザーネーム:<a href="/users/<%= t.user.id %>"><%= t.user.name %></a>
              <br><%= image_tag t.image_url, size: "250x200" if t.image? %><br>
              <br><%= t.body %></br>
              <% t.tags.each do |tag| %>
              <br><%= tag.name %></br>
              <% end %>
          <% if user_signed_in? %>
              <% if current_user.already_liked?(t) %>
                  <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                      <i class="fas fa-heart"></i><%= t.likes.count %>
                  <% end %>
              <% else %>
                  <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                        <i class="far fa-heart"></i><%= t.likes.count %>
                  <% end %>
              <% end %>
          <% else %>
            <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>

          <%= t.created_at %>
          <%= link_to "詳細へ", post_path(t.id) %>
          <% if user_signed_in? && current_user.id == t.user_id %>
            <%= link_to "編集する", edit_post_path(t.id) %>
            <%= button_to "削除する", post_path(t.id), method: :delete %>
          <% end %>      
        </div>
      <p id="notice"><%= notice %></p>
    <% elsif i==2 %>
      2位
      <div class="rank2">
        ユーザーネーム:<a href="/users/<%= t.user.id %>"><%= t.user.name %></a>
        <br><%= image_tag t.image_url, size: "250x200" if t.image? %></br>
        <br><%= t.body %></br>
        <% t.tags.each do |tag| %>
          <br><%= tag.name %></br>
        <% end %>
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
        <% else %>
          <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
          <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
        <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>

        
        <%= t.created_at %>
        <%= link_to "詳細へ", post_path(t.id) %>
        <% if user_signed_in? && current_user.id == t.user_id %>
          <%= link_to "編集する", edit_post_path(t.id) %>
          <%= button_to "削除する", post_path(t.id), method: :delete %>
        <% end %>      
      </div>
      <p id="notice"><%= notice %></p>
    <% elsif i==3 %>
      3位
      <div class="rank3">
            
        ユーザーネーム:<a href="/users/<%= t.user.id %>"><%= t.user.name %></a>
          <br><%= image_tag t.image_url, size: "250x200" if t.image? %></br>
          <br><%= t.body %></br>
          <% t.tags.each do |tag| %>
            <br><%= tag.name %></br>
          <% end %>
          <% if user_signed_in? %>
            <% if current_user.already_liked?(t) %>
              <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% else %>
            <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% end %>
          <% else %>
            <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>

          
          <%= t.created_at %>
          <%= link_to "詳細へ", post_path(t.id) %>
          <% if user_signed_in? && current_user.id == t.user_id %>
            <%= link_to "編集する", edit_post_path(t.id) %>
            <%= button_to "削除する", post_path(t.id), method: :delete %>
          <% end %>      
        </div>
        <p id="notice"><%= notice %></p>

  <% end %>
  </div>
  <% end %>
</div>  

<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 100%;
}
</style>

<!-- js部分 -->
<script>
    function initMap() {

      //初期表示位置
      let latlng = new google.maps.LatLng(38.60, 139.5);
      //デザイン
      let styles = [
           {
            stylers: [
             { "saturation": 0 },
             { "lightness": 0 }
            ]
           }
          ];

      let map = new google.maps.Map(document.getElementById('map'), {
          zoom: 5.5,
          styles: styles,
          center: latlng
      });
      let transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);

      //複数マーカー ここから
      <% @page.each do |post|%>
        ( function() { 
          let markerLatLng = new google.maps.LatLng({lat: <%= post.lat %>, lng: <%= post.lng %>}); // 緯度経度のデータ作成
          let marker = new google.maps.Marker({ 
            position: markerLatLng, 
            map: map 
          });
    　　　//マーカーをクリックしたとき、詳細情報を表示
          let infowindow = new google.maps.InfoWindow({
            position: markerLatLng,
            content: "<a href='<%= post_url(post.id) %>' target='_blank'><%= post.body %></a>"
          }); //ここで詳細ページへのリンクを表示させる
          marker.addListener('click', function() {
            infowindow.open(map, marker);
          });

       })();
      <% end %>
      //複数マーカー ここまで  
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>
</body>





app/views/posts/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>
<div class="head">
  <%= current_user.id %>
  <h1>新規投稿</h1>
  <h5>Hobbyshare</h5>
</div>
<div class ="main">
  <%= form_with(model: @post, local: true) do |f| %>
    <div class="field1">
      <%= f.label :写真 %>
      <%= f.file_field :image %>
    </div>

    <div class="field2">
      <%= f.label :投稿内容 %>
      <%= f.text_field :body, :size => "100x100" %>
    </div>

    <div class="check_box">
      <strong>タグ</strong>
      <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class ="tag_box">
        <%= tag.label do %>
        <%= tag.check_box %>
        <%= tag.text %>
        <% end %>
      </div>
      <% end %>
    </div>

    <div class="field3">
      <%= f.label :lat,"緯度" %>
      <%= f.text_field :lat,:value =>"緯度", id: :lat %>
      <%= f.label :lng,"経度" %>
      <%= f.text_field :lng,:value =>"経度", id: :lng %>
    </div>

    <div class="actions">
      <%= f.submit "投稿する" %>
    </div>
    
  <% end %>
</div>


<h2>Map</h2>

<input id="address" type="textbox" value="GeekSalon">
<input type="button" value="検索" onclick="codeAddress()">
<p>マーカーをドラック＆ドロップで位置の調整ができます。<p>
<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: 35.6803997, lng:139.7690174},  //東京
    zoom: 15,

  });
}

//検索後のマップ作成
let geocoder
let aft
function codeAddress(){
  let inputAddress = document.getElementById('address').value;
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
        //マーカーが複数できないようにする
        if (aft == true){
            marker.setMap(null);
        }

        //新しくマーカーを作成する
        map.setCenter(results[0].geometry.location);
            marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location,
            draggable: true // ドラッグ可能にする
        });

        //二度目以降か判断
        aft = true

        //検索した時に緯度経度を入力する
        document.getElementById('lat').value = results[0].geometry.location.lat();
        document.getElementById('lng').value = results[0].geometry.location.lng();

        // マーカーのドロップ（ドラッグ終了）時のイベント
        google.maps.event.addListener( marker, 'dragend', function(ev){
            // イベントの引数evの、プロパティ.latLngが緯度経度
            document.getElementById('lat').value = ev.latLng.lat();
            document.getElementById('lng').value = ev.latLng.lng();
        });
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>


app/views/posts/show.html.erb
<%= stylesheet_link_tag 'post.show', :media => "all" %>
<div class ="top">
  <h1>投稿詳細</h1>
</div>
<div class="post1">
  <img src= <%= @post.image_url %> width="400" height="400" >
  <br><%= @post.body %></br>
  <br><%= @post.created_at %></br>
  <% if user_signed_in? %>
      <% if current_user.already_liked?(@post) %>
          <%= link_to post_like_path(@post), method: :delete do %>
            <i class="fas fa-heart"></i><%= @post.likes.count %>
          <% end %>
      <% else %>
          <%= link_to post_likes_path(@post), method: :post do %>
            <i class="far fa-heart"></i><%= @post.likes.count %>
          <% end %>
      <% end %>
  <% else %>
      <i class="far fa-heart"></i><%= @post.likes.count %>  
  <% end %>
  <% @post.tags.each do |tag| %>
    <%= tag.name %>
  <% end %>  
</div>

<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 100%;
}
</style>

<!-- js部分 -->
<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: <%= @post.lat %>, lng: <%= @post.lng %>},
    zoom: 15,
  });

   marker = new google.maps.Marker({
    position:  {lat: <%= @post.lat %>, lng: <%= @post.lng %>},
    map: map
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>

<div class="message-wrapper">
  <p>コメント一覧</p>
  <% @messages.each do |m| %>
    <div>
      <%= m.user.email unless m.user.blank? %>
      <br>
      <%= m.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@post, @message], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>

</div>
<h2>いいねしたユーザー</h2>
<% @post.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>