hobbyshare/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
#get 'posts/index' => 'posts#index'
#get 'posts/new' => 'posts#new'
#post 'posts' => 'posts#create' 
#get 'posts/:id' => 'posts#show',as: 'post'
#patch 'posts/:id' => 'posts#update'
#delete 'posts/:id' => 'posts#destroy'
#get 'posts/:id/edit' => 'posts#edit', as:'edit_post'
get 'hello/index' => 'hello#index'
root 'hello#index'
#resources :likes, only: [:create, :destroy]
end

hobbyshare/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

hobbyshare/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

hobbyshare/app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user    
    has_many :post_tags, dependent: :destroy
    has_many :tags, through: :post_tags
end

hobbyshare/app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

hobbyshare/app/models/tag.rb
class Tag < ApplicationRecord
    has_many :post_tags, dependent: :destroy
    has_many :posts, through: :post_tags
end

hobbyshare/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  def already_liked?(post)
       self.likes.exists?(post_id: post.id)
     end
 end

hobbyshare/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

hobbyshare/app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

hobbyshare/app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(post_id: params[:post_id]) #user_idとpost_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

hobbyshare/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  
    def index
        @posts =Post.all
        @post = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
    end
   
    def new
       @post = Post.new
    end
   
    def create
       post = Post.new(post_params)
       post.user_id = current_user.id
       if post.save
         redirect_to :action => "index"
       else
         redirect_to :action => "new"
       end
    end
    
    def show
        @post = Post.find(params[:id])
    end
    
    def edit
        @post = Post.find(params[:id])
    end

    def update
        post = Post.find(params[:id])
        if post.update(post_params)
          redirect_to :action => "show", :id => post.id
        else
          redirect_to :action => "new"
        end
    end
    def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to action: :index
      end
    def post_params
      params.require(:post).permit(:body, :title, tag_ids: [])
    end
    private
    def post_params
        params.require(:post).permit(:body, :image)
    end

end    

 

hobbyshare/app/helpers/application_helper.rb
module ApplicationHelper
end

hobbyshare/app/helpers/hello_helper.rb
module HelloHelper
end

hobbyshare/app/helpers/likes_helper.rb
module LikesHelper
end

hobbyshare/app/helpers/posts_helper.rb
module PostsHelper
end

hobbyshare/app/views/hello/index.html.erb
<h1>My Pageへようこそ</h1>
<%= link_to "ログイン", posts_path %>
<%= link_to "新規登録", new_user_registration_path %>

hobbyshare/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hobbyshare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

hobbyshare/app/views/posts/_form.html.erb
<div class="check_box">
    <span>タグ</span>
    <%= form.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
     <div>
       <%= tag.label do %>
         <%= tag.check_box %>
         <%= tag.text %>
       <% end %>
     </div>
   <% end %>
 </div>
 <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

hobbyshare/app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

hobbyshare/app/views/posts/index.html.erb
<h1>Hobbyshare</h1>
<h3>投稿一覧</h3>
<%= link_to "新規投稿へ", new_post_path %>
<div class="posts-container">
  <% @posts.each do |t| %>
  <div class="post">
    <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <%= t.body %>
    <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
        <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
        <i class="fas fa-heart"></i><%= t.likes.count %>
      <% end %>
    <% else %>
      <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
      <i class="far fa-heart"></i><%= t.likes.count %>
      <% end %>
    <% end %>
    <% else %>
      <i class="far fa-heart"></i><%= t.likes.count %>
    <% end %>

    #<%= t.user.email %>
    <%= t.created_at %>
    <%= link_to "詳細へ", post_path(t.id) %>
    <% if user_signed_in? && current_user.id == t.user_id %>
       <%= link_to "編集する", edit_post_path(t.id) %>
       <%= button_to "削除する", post_path(t.id), method: :delete %>
    <% end %>
    <% t.tags.each do |tag| %>
      <%= tag.name %>
    <% end %>      
  </div>
  <p id="notice"><%= notice %></p>

  <h1>Posts</h1>
  #ここから追記
  <%= form_tag posts_path, method: :get, class: 'boards__searchForm' do %>
        <%= select_tag :tag_id,
                       options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                       {
                         prompt: 'タグで絞り込み検索',
                         onchange: 'submit(this.form);'
                       }
        %>
      <% end %>
  <% end %>
  <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>

</div>

hobbyshare/app/views/posts/new.html.erb
<h1>Hobbyshare</h1>
<h3>新規投稿</h3>
<%= form_for @post do |f| %>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="check_box">
    <span>タグ</span>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
    <div>
      <%= tag.label do %>
      <%= tag.check_box %>
      <%= tag.text %>
      <% end %>
    </div>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <%= f.submit "投稿する" %>
<% end %>
<%= link_to "投稿一覧に戻る", posts_path %>

hobbyshare/app/views/posts/show.html.erb
<h1>Hobbyshare</h1>
<h2>投稿詳細</h2>

<div class="post">
  <p><%= @post.user.email %></p>
  <h3><%= @post.body %></h3>
  <p><%= @post.created_at %></p>

  
<% if user_signed_in? %>
    <% if current_user.already_liked?(@post) %>
        <%= link_to post_like_path(@post), method: :delete do %>
          <i class="fas fa-heart"></i><%= @post.likes.count %>
        <% end %>
    <% else %>
        <%= link_to post_likes_path(@post), method: :post do %>
          <i class="far fa-heart"></i><%= @post.likes.count %>
        <% end %>
    <% end %>
<% else %>
    <i class="far fa-heart"></i><%= @post.likes.count %>  
<% end %>
<% @post.tags.each do |tag| %>
  <%= tag.name %>
<% end %>  

</div>

<h2>いいねしたユーザー</h2>
<% @post.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<%= link_to "編集する", edit_post_path(@post.id) %>
<%= link_to "投稿一覧に戻る", posts_path %>

hobbyshare/app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

hobbyshare/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>